name: mtg_stream_bloc
description: StreamController Bloc State Managment.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.1.15
  dart_code_metrics: ^5.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  injectable_generator: ^2.1.3
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
